version: "3.7"

services:
  orm:
    container_name: orm
    image: orm
    build:
      context: ./
      dockerfile: install/docker/Dockerfile
      target: orm
    working_dir: /var/www/html/orm
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html/orm
      - composer-data:/var/www/html/orm/install/vendor # 这一行的意思是容器里该文件夹不会被宿主机所覆盖
    restart: on-failure

  nginx:
    container_name: orm_nginx
    image: orm_nginx
    build:
      context: ./
      dockerfile: install/docker/Dockerfile
      target: nginx
    working_dir: /var/www/html/orm
    depends_on:
      - orm
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/orm
      - composer-data:/var/www/html/orm/install/vendor # 这一行的意思是容器里该文件夹不会被宿主机所覆盖
    environment:
      ENABLE_CRONTAB: "true"
    restart: on-failure

  redis:
    image: redis:4.0.1
    # image: redis:6.2.6
    container_name: orm_redis
    command: redis-server --requirepass orm
    ports:
        - 6379:6379
    environment:
      TZ: Asia/Shanghai
    restart: on-failure

volumes:
  composer-data: